"""Dual-Agent Node Implementation - Story 2.9.

This module provides the DualAgentNode class which:
- Coordinates Independent and Evaluator agents
- Filters private_reasoning from Independent Agent output before passing to Evaluator
- Supports iteration loop when Evaluator returns NEEDS_REVISION verdict
- Passes previous feedback to Independent Agent on retry iterations
- Tracks and reports iteration count in final result
- Handles edge cases where Independent Agent returns malformed output
- Ensures Evaluator never receives private_reasoning field
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import structlog

if TYPE_CHECKING:
    from structlog import BoundLogger as StructlogBoundLogger

    from autoBMAD.docuswarm.config import Config as AgentConfig
    from autoBMAD.docuswarm.pipeline.state import PipelineState

from autoBMAD.docuswarm.agents.evaluator import EvaluatorAgent
from autoBMAD.docuswarm.agents.independent import IndependentAgent
from autoBMAD.docuswarm.context.audit import IsolationAuditLogger
from autoBMAD.docuswarm.context.filter import ContextFilter
from autoBMAD.docuswarm.context.isolation import ContextIsolationError, ContextManager
from autoBMAD.docuswarm.llm.session_manager import KimiSessionManager
from autoBMAD.docuswarm.nodes.iteration import IterationController
from autoBMAD.docuswarm.pipeline.escalation import EscalationHandler, EscalationReason
from autoBMAD.docuswarm.pipeline.force_completion import (
    ForceCompletion,
    create_force_completion,
)
from autoBMAD.docuswarm.pipeline.metrics import MetricsCollector
from autoBMAD.docuswarm.pipeline.quality import QualityConfig, VerdictDeterminer
from autoBMAD.docuswarm.pipeline.questions import QuestionHandler

# Type alias for force completion (optional, for type hints)
ForceCompletionRecord = ForceCompletion | None

# Type aliases for better type inference
IndependentOutput = dict[str, Any]
EvaluatorOutput = dict[str, Any]


@dataclass
class NodeResult:
    """Result from DualAgentNode execution.

    Attributes:
        deliverable: The deliverable created by Independent Agent.
        questions: Questions generated by Independent Agent.
        evaluation: Evaluation result from Evaluator Agent.
        iteration: Number of iterations executed (1-indexed).
        timestamp: Execution timestamp.
        force_completion: Force completion record if triggered (optional).
    """

    deliverable: dict[str, Any]
    questions: list[dict[str, Any]]
    evaluation: dict[str, Any]
    iteration: int
    timestamp: datetime
    force_completion: ForceCompletion | None = None


class DualAgentNodeError(Exception):
    """Base exception for DualAgentNode errors."""

    pass


class IndependentExecutionError(DualAgentNodeError):
    """Raised when Independent Agent execution fails."""

    pass


class EvaluatorExecutionError(DualAgentNodeError):
    """Raised when Evaluator Agent execution fails."""

    pass


class EscalationError(DualAgentNodeError):
    """Raised when node execution is blocked and requires escalation."""

    pass


class DualAgentNode:
    """Dual-Agent Node for coordinating Independent and Evaluator agents.

    This node executes a dual-agent pattern:
    1. Execute Independent Agent to generate deliverable and questions
    2. Filter private_reasoning from Independent output
    3. Execute Evaluator Agent to score the deliverable
    4. If NEEDS_REVISION, iterate with feedback (up to max_iterations)
    5. Return combined result

    Attributes:
        node_id: The node identifier.
        independent_agent: The Independent Agent instance.
        evaluator_agent: The Evaluator Agent instance.
        max_iterations: Maximum number of iteration cycles.
    """

    DEFAULT_MAX_ITERATIONS = 3

    def __init__(
        self,
        config: AgentConfig,
        independent_agent: IndependentAgent,
        evaluator_agent: EvaluatorAgent,
        node_id: str,
        max_iterations: int = DEFAULT_MAX_ITERATIONS,
        context_manager: ContextManager | None = None,
        context_filter: ContextFilter | None = None,
        audit_logger: IsolationAuditLogger | None = None,
        # Quality control components (Story 5.8)
        iteration_controller: IterationController | None = None,
        question_handler: QuestionHandler | None = None,
        escalation_handler: EscalationHandler | None = None,
        metrics_collector: MetricsCollector | None = None,
        quality_config: QualityConfig | None = None,
    ) -> None:
        """Initialize the DualAgentNode.

        Args:
            config: Agent configuration object.
            independent_agent: The Independent Agent instance.
            evaluator_agent: The Evaluator Agent instance.
            node_id: The node identifier.
            max_iterations: Maximum number of iteration cycles (default: 3).
            context_manager: ContextManager for building agent contexts (optional).
            context_filter: ContextFilter for removing private fields (optional).
            audit_logger: IsolationAuditLogger for auditing operations (optional).
            iteration_controller: IterationController for tracking iterations (optional).
            question_handler: QuestionHandler for collecting questions (optional).
            escalation_handler: EscalationHandler for handling escalations (optional).
            metrics_collector: MetricsCollector for recording metrics (optional).
            quality_config: QualityConfig for verdict determination (optional).
        """
        self.config = config
        self.independent_agent = independent_agent
        self.evaluator_agent = evaluator_agent
        self.node_id = node_id
        self.max_iterations = max_iterations

        # Isolation components - use defaults if not provided
        self.context_manager = context_manager or ContextManager()
        self.context_filter = context_filter or ContextFilter()
        self.audit_logger = audit_logger or IsolationAuditLogger()

        # Quality control components (Story 5.8)
        self.iteration_controller = iteration_controller
        self.question_handler = question_handler
        self.escalation_handler = escalation_handler
        self.metrics_collector = metrics_collector
        self.quality_config = quality_config or QualityConfig()

        self.logger: StructlogBoundLogger = structlog.get_logger().bind(
            node=self.__class__.__name__,
            node_id=node_id,
        )

    def _filter_for_evaluator(self, independent_output: IndependentOutput) -> IndependentOutput:
        """Filter Independent Agent output to remove private_reasoning.

        This is CRITICAL for security - private_reasoning must NEVER reach Evaluator.

        Args:
            independent_output: Raw output from Independent Agent.

        Returns:
            Filtered dict without private_reasoning field.
        """
        filtered: IndependentOutput = {}

        # Copy deliverable
        if "deliverable" in independent_output:
            deliverable = independent_output["deliverable"]
            assert isinstance(deliverable, dict)
            filtered["deliverable"] = deliverable.copy()

        # Copy questions
        if "questions" in independent_output:
            questions = independent_output["questions"]
            assert isinstance(questions, list)
            filtered["questions"] = questions.copy()

        # Explicitly exclude private_reasoning
        # (already excluded by not copying it)

        return filtered

    def _build_independent_context(
        self,
        subject_context: str,
        task: str,
        previous_feedback: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Build context for Independent Agent execution.

        Args:
            subject_context: The subject/context of the task.
            task: The task description.
            previous_feedback: Optional feedback from previous iteration.

        Returns:
            Context dict for Independent Agent.
        """
        context: dict[str, Any] = {
            "subject_context": subject_context,
            "task": task,
        }

        # Add previous feedback if available
        if previous_feedback:
            issues_found: list[str] = previous_feedback.get("issues_found", [])
            suggestions: list[str] = previous_feedback.get("suggestions", [])
            verdict: str = previous_feedback.get("verdict", "UNKNOWN")
            alignment_score: float = previous_feedback.get("alignment_score", 0.0)

            feedback_text = f"""
## Previous Feedback

The previous attempt received the following feedback:

**Verdict**: {verdict}
**Alignment Score**: {alignment_score}

**Issues Found**:
{chr(10).join(f"- {issue}" for issue in issues_found)}

**Suggestions**:
{chr(10).join(f"- {suggestion}" for suggestion in suggestions)}

Please address these issues in your revised deliverable.
"""
            context["task"] = task + feedback_text

        return context

    async def execute(
        self,
        subject_context: str,
        task: str,
        pipeline_id: str = "",
    ) -> NodeResult:
        """Execute the dual-agent pattern with context isolation.

        This method implements the dual-agent pattern with full context isolation:
        1. Build Independent Agent context using ContextManager
        2. Execute Independent Agent to generate deliverable and questions
        3. Filter private fields using ContextFilter
        4. Build Evaluator Agent context using ContextManager
        5. Execute Evaluator Agent to score the deliverable
        6. If NEEDS_REVISION, iterate with feedback (up to max_iterations)
        7. Return combined result with audit logging

        Args:
            subject_context: The subject/context of the task.
            task: The task description.
            pipeline_id: The pipeline identifier for file output (Story 11.1).

        Returns:
            NodeResult containing deliverable, questions, evaluation, iteration, and timestamp.

        Raises:
            DualAgentNodeError: If execution fails.
            ContextIsolationError: If private fields leak to Evaluator.
        """
        self.logger.info(
            "starting_dual_agent_execution",
            node_id=self.node_id,
            task=task[:100],
        )

        iteration = 0
        previous_feedback: dict[str, Any] | None = None
        final_deliverable: dict[str, Any] = {}
        final_questions: list[dict[str, Any]] = []
        final_evaluation: dict[str, Any] = {}
        final_force_completion: ForceCompletion | None = None

        # Use provided pipeline_id or generate one for audit logging
        # If pipeline_id is provided from outside (e.g., from node executor), use it
        if not pipeline_id:
            pipeline_id = f"{self.node_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}"

        while iteration < self.max_iterations:
            iteration += 1

            self.logger.info(
                "iteration_start",
                iteration=iteration,
                max_iterations=self.max_iterations,
            )

            # Step 1: Build Independent Agent context and execute
            try:
                # Log context build for Independent Agent
                self.audit_logger.log_context_build(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={
                        "subject_context": subject_context,
                        "has_feedback": previous_feedback is not None,
                    },
                )

                # Build context using ContextManager
                # Include pipeline_id at top level for IndependentAgent (Story 11.1)
                independent_context = self.context_manager.build_independent_context(
                    subject_context={"subject": subject_context, "task": task},
                    iteration_feedback=previous_feedback,
                )
                # Add pipeline_id at top level (IndependentAgent expects it there)
                independent_context["pipeline_id"] = pipeline_id

                independent_output = await self.independent_agent.execute(independent_context)

                # Handle potentially malformed output with defaults
                independent_deliverable = independent_output.get("deliverable")
                if isinstance(independent_deliverable, dict):
                    final_deliverable.clear()
                    final_deliverable.update(cast(dict[str, Any], independent_deliverable))

                independent_questions = independent_output.get("questions")
                if isinstance(independent_questions, list):
                    final_questions.clear()
                    final_questions.extend(cast(list[dict[str, Any]], independent_questions))

            except Exception as e:
                self.logger.error("independent_agent_failed", iteration=iteration, error=str(e))
                raise IndependentExecutionError(
                    f"Independent Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 2: Filter private fields before passing to Evaluator
            try:
                filtered_output = self.context_filter.filter_for_evaluator(independent_output)

                # Log filter operation
                fields_removed = [
                    field
                    for field in [
                        "private_reasoning",
                        "tool_call_history",
                        "internal_notes",
                        "iteration_feedback",
                    ]
                    if field in independent_output
                ]
                self.audit_logger.log_filter_operation(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    fields_removed=fields_removed,
                )

            except Exception as e:
                self.logger.error("filter_operation_failed", iteration=iteration, error=str(e))
                self.audit_logger.log_potential_violation(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={"error": str(e), "stage": "filter"},
                )
                raise

            # Step 3: Build Evaluator context and execute
            try:
                # Log context build for Evaluator Agent
                self.audit_logger.log_context_build(
                    agent_type="evaluator",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={
                        "deliverable_keys": list(filtered_output.get("deliverable", {}).keys())
                    },
                )

                # Build evaluator context using ContextManager (validates no private fields)
                evaluator_context = self.context_manager.build_evaluator_context(
                    subject_context={"subject": subject_context},
                    deliverable=filtered_output.get("deliverable"),
                )

                evaluation = await self.evaluator_agent.execute(evaluator_context)
                final_evaluation = evaluation

            except ContextIsolationError as e:
                # Log potential violation
                self.logger.error(
                    "context_isolation_violation",
                    iteration=iteration,
                    error=str(e),
                )
                self.audit_logger.log_potential_violation(
                    agent_type="evaluator",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={"error": str(e), "stage": "context_build"},
                )
                raise

            except Exception as e:
                self.logger.error("evaluator_agent_failed", iteration=iteration, error=str(e))
                raise EvaluatorExecutionError(
                    f"Evaluator Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 4: Check verdict and decide if we need to iterate
            verdict: str = evaluation.get("verdict", "NEEDS_REVISION")

            self.logger.info(
                "evaluation_complete",
                iteration=iteration,
                verdict=verdict,
                alignment_score=evaluation.get("alignment_score", 0.0),  # type: ignore[arg-type]
            )

            if verdict == "APPROVED":
                # Success - exit the loop
                self.logger.info(
                    "dual_agent_approved",
                    iteration=iteration,
                )
                break
            elif verdict == "FORCE_APPROVED":
                # Force complete - exit the loop with warning
                alignment_score: float = evaluation.get("alignment_score", 0.0)  # type: ignore[assignment]
                issues_list: list[Any] = evaluation.get("issues_found", [])  # type: ignore[assignment]

                # Create force completion record
                final_force_completion = create_force_completion(
                    node_id=self.node_id,
                    final_score=alignment_score,
                    threshold=0.50,  # Default escalation threshold
                    iterations=iteration,
                    issues_remaining=[str(i) for i in issues_list],
                )

                # Log the force completion warning
                self.logger.warning(
                    "force_completion_triggered",
                    node_id=self.node_id,
                    iteration=iteration,
                    alignment_score=alignment_score,
                    force_complete_warning=final_force_completion.warning,
                )
                break
            elif verdict == "BLOCKED":
                # Can't proceed - exit the loop
                self.logger.warning(
                    "dual_agent_blocked",
                    iteration=iteration,
                )
                break
            else:
                # NEEDS_REVISION - prepare for next iteration
                eval_alignment_score: float = evaluation.get("alignment_score", 0.0)
                eval_issues_found: list[Any] = evaluation.get("issues_found", [])
                eval_suggestions: list[Any] = evaluation.get("suggestions", [])

                previous_feedback = {
                    "alignment_score": eval_alignment_score,
                    "verdict": verdict,
                    "issues_found": eval_issues_found,
                    "suggestions": eval_suggestions,
                }

                self.logger.info(
                    "iteration_needs_revision",
                    iteration=iteration,
                    preparing_for_next=True,
                )

        # Return the combined result
        result = NodeResult(
            deliverable=final_deliverable,
            questions=final_questions,
            evaluation=final_evaluation,
            iteration=iteration,
            timestamp=datetime.now(),
            force_completion=final_force_completion,
        )

        self.logger.info(
            "dual_agent_execution_complete",
            iteration=iteration,
            verdict=final_evaluation.get("verdict", "UNKNOWN"),
        )

        return result

    async def execute_with_iteration(
        self,
        state: dict[str, Any],
    ) -> NodeResult:
        """Execute node with full iteration and quality control (Story 5.8).

        This method implements the iteration loop with quality control:
        1. Start iteration using IterationController
        2. Get accumulated feedback from previous iterations
        3. Execute single iteration (Independent + Evaluator)
        4. Collect questions using QuestionHandler
        5. Record iteration using IterationController
        6. Determine verdict using VerdictDeterminer
        7. Handle verdict (APPROVED/FORCE_APPROVED/BLOCKED/NEEDS_REVISION)
        8. Record metrics using MetricsCollector
        9. Escalate on BLOCKED verdict

        Args:
            state: Pipeline state dict containing pipeline_id, subject_context, task.

        Returns:
            NodeResult containing deliverable, questions, evaluation, iteration, and timestamp.

        Raises:
            EscalationError: When BLOCKED verdict occurs after max iterations.
        """
        if not self.iteration_controller:
            raise DualAgentNodeError("IterationController is required for execute_with_iteration")

        pipeline_id = state.get(
            "pipeline_id", f"{self.node_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}"
        )
        subject_context = state.get("subject_context", "")
        task = state.get("task", "")

        final_deliverable: dict[str, Any] = {}
        final_questions: list[dict[str, Any]] = []
        final_evaluation: dict[str, Any] = {}
        final_force_completion: ForceCompletion | None = None
        result: NodeResult | None = None

        # Create verdict determiner
        verdict_determiner = VerdictDeterminer(self.quality_config)

        while True:
            # Start iteration
            iteration = self.iteration_controller.start_iteration(self.node_id)

            self.logger.info(
                "iteration_start",
                iteration=iteration,
                max_iterations=self.max_iterations,
            )

            # Get accumulated feedback
            accumulated_feedback = self.iteration_controller.get_accumulated_feedback(self.node_id)

            # Step 1: Execute Independent Agent
            try:
                independent_context = self.context_manager.build_independent_context(
                    subject_context={"subject": subject_context, "task": task},
                    iteration_feedback=accumulated_feedback,
                )

                independent_output = await self.independent_agent.execute(independent_context)

                # Handle potentially malformed output with defaults
                independent_deliverable = independent_output.get("deliverable")
                if isinstance(independent_deliverable, dict):
                    final_deliverable.clear()
                    final_deliverable.update(cast(dict[str, Any], independent_deliverable))

                independent_questions = independent_output.get("questions")
                if isinstance(independent_questions, list):
                    final_questions.clear()
                    final_questions.extend(cast(list[dict[str, Any]], independent_questions))

            except Exception as e:
                self.logger.error("independent_agent_failed", iteration=iteration, error=str(e))
                raise IndependentExecutionError(
                    f"Independent Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 2: Filter and execute Evaluator Agent
            try:
                filtered_output = self.context_filter.filter_for_evaluator(independent_output)

                evaluator_context = self.context_manager.build_evaluator_context(
                    subject_context={"subject": subject_context},
                    deliverable=filtered_output.get("deliverable"),
                )

                evaluation = await self.evaluator_agent.execute(evaluator_context)
                final_evaluation = evaluation

            except ContextIsolationError as e:
                self.logger.error("context_isolation_violation", iteration=iteration, error=str(e))
                raise
            except Exception as e:
                self.logger.error("evaluator_agent_failed", iteration=iteration, error=str(e))
                raise EvaluatorExecutionError(
                    f"Evaluator Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 3: Collect questions
            if self.question_handler and final_questions:
                # Transform question format from {question, priority, context} to {question_text, priority, context}
                transformed_questions: list[dict[str, Any]] = []
                for q in final_questions:
                    transformed_q = {**q, "node_id": self.node_id}
                    if "question" in transformed_q and "question_text" not in transformed_q:
                        transformed_q["question_text"] = transformed_q.pop("question")
                    transformed_questions.append(transformed_q)
                self.question_handler.collect_questions(
                    pipeline_id,
                    transformed_questions,
                )

            # Step 4: Record iteration
            self.iteration_controller.record_iteration(
                node_id=self.node_id,
                verdict=evaluation.get("verdict", "NEEDS_REVISION"),
                alignment_score=evaluation.get("alignment_score", 0.0),
                issues=evaluation.get("issues_found", []),
                suggestions=evaluation.get("suggestions", []),
            )

            # Step 5: Determine verdict using VerdictDeterminer
            alignment_score = evaluation.get("alignment_score", 0.0)
            raw_verdict = evaluation.get("verdict", "NEEDS_REVISION")

            # If raw verdict is already terminal, use it directly
            if raw_verdict in ("APPROVED", "FORCE_APPROVED", "BLOCKED"):
                verdict = raw_verdict
            else:
                # Use VerdictDeterminer to determine verdict
                determined = verdict_determiner.determine_verdict(
                    alignment_score=alignment_score,
                    node_id=self.node_id,
                    iteration=iteration,
                    max_iterations=self.max_iterations,
                )
                verdict = determined.value

            # Update evaluation with determined verdict
            final_evaluation["verdict"] = verdict

            # Step 6: Handle verdict
            if verdict == "APPROVED":
                self.logger.info("iteration_approved", iteration=iteration)
                # Record metrics
                if self.metrics_collector:
                    self.metrics_collector.record_node_completion(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        final_score=alignment_score,
                        iterations=iteration,
                        verdict=verdict,
                        force_completed=False,
                    )
                result = NodeResult(
                    deliverable=final_deliverable,
                    questions=final_questions,
                    evaluation=final_evaluation,
                    iteration=iteration,
                    timestamp=datetime.now(),
                    force_completion=None,
                )
                break

            elif verdict == "FORCE_APPROVED":
                self.logger.warning("iteration_force_approved", iteration=iteration)
                alignment_score_val = evaluation.get("alignment_score", 0.0)
                issues_list = evaluation.get("issues_found", [])

                # Get node-specific thresholds for force completion record
                node_thresholds = self.quality_config.get_thresholds(self.node_id)

                # Create force completion record
                final_force_completion = create_force_completion(
                    node_id=self.node_id,
                    final_score=alignment_score_val,
                    threshold=node_thresholds.escalation,
                    iterations=iteration,
                    issues_remaining=[str(i) for i in issues_list],
                )

                # Record metrics with force_completed=True
                if self.metrics_collector:
                    self.metrics_collector.record_node_completion(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        final_score=alignment_score_val,
                        iterations=iteration,
                        verdict=verdict,
                        force_completed=True,
                    )

                result = NodeResult(
                    deliverable=final_deliverable,
                    questions=final_questions,
                    evaluation=final_evaluation,
                    iteration=iteration,
                    timestamp=datetime.now(),
                    force_completion=final_force_completion,
                )
                break

            elif verdict == "BLOCKED":
                self.logger.error("iteration_blocked", iteration=iteration)
                # Trigger escalation
                if self.escalation_handler:
                    self.escalation_handler.escalate(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        reason=EscalationReason.MAX_ITERATIONS,
                        alignment_score=alignment_score,
                        issues=evaluation.get("issues_found", []),
                    )
                raise EscalationError(f"Node {self.node_id} blocked - escalation required")

            # NEEDS_REVISION - continue loop if should iterate
            if not self.iteration_controller.should_iterate(self.node_id):
                self.logger.warning("max_iterations_reached_no_approval")
                # At max iterations without approval - determine final state using node-specific thresholds
                node_thresholds = self.quality_config.get_thresholds(self.node_id)
                if alignment_score >= node_thresholds.escalation:
                    verdict = "FORCE_APPROVED"
                    self.logger.warning("force_approved_at_max_iterations", score=alignment_score)
                    if self.metrics_collector:
                        self.metrics_collector.record_node_completion(
                            pipeline_id=pipeline_id,
                            node_id=self.node_id,
                            final_score=alignment_score,
                            iterations=iteration,
                            verdict=verdict,
                            force_completed=True,
                        )
                    result = NodeResult(
                        deliverable=final_deliverable,
                        questions=final_questions,
                        evaluation=final_evaluation,
                        iteration=iteration,
                        timestamp=datetime.now(),
                        force_completion=final_force_completion,
                    )
                else:
                    verdict = "BLOCKED"
                    self.logger.error("blocked_at_max_iterations", score=alignment_score)
                    if self.escalation_handler:
                        self.escalation_handler.escalate(
                            pipeline_id=pipeline_id,
                            node_id=self.node_id,
                            reason=EscalationReason.MAX_ITERATIONS,
                            alignment_score=alignment_score,
                            issues=evaluation.get("issues_found", []),
                        )
                    raise EscalationError(
                        f"Node {self.node_id} blocked at max iterations - escalation required"
                    )
                break

            # Prepare feedback for next iteration
            self.logger.info(
                "iteration_needs_revision",
                iteration=iteration,
                preparing_for_next=True,
            )

        return result


def create_dual_agent_node(
    config: AgentConfig,
    session_manager: KimiSessionManager,
    node_id: str,
    project_root: Path | None = None,
    max_iterations: int = DualAgentNode.DEFAULT_MAX_ITERATIONS,
) -> DualAgentNode:
    """Create a DualAgentNode with configured agents.

    Args:
        config: Agent configuration.
        session_manager: KimiSessionManager for SDK interactions.
        node_id: The node identifier for persona/criteria loading.
        project_root: Root directory of the project.
        max_iterations: Maximum number of iteration cycles.

    Returns:
        Configured DualAgentNode instance.
    """
    from autoBMAD.docuswarm.agents.evaluator import create_evaluator_agent
    from autoBMAD.docuswarm.agents.independent import create_independent_agent

    # Create agents using convenience functions
    independent_agent = create_independent_agent(
        config=config,
        session_manager=session_manager,
        node_id=node_id,
        project_root=project_root,
    )

    evaluator_agent = create_evaluator_agent(
        config=config,
        session_manager=session_manager,
        node_id=node_id,
        project_root=project_root,
    )

    return DualAgentNode(
        config=config,
        independent_agent=independent_agent,
        evaluator_agent=evaluator_agent,
        node_id=node_id,
        max_iterations=max_iterations,
    )


__all__ = [
    "DualAgentNode",
    "DualAgentNodeError",
    "IndependentExecutionError",
    "EvaluatorExecutionError",
    "EscalationError",
    "NodeResult",
    "create_dual_agent_node",
    "create_node_executor",
]


def create_node_executor(node_id: str, session_manager: KimiSessionManager):
    """Create a node executor function for LangGraph pipeline.

    This factory function returns an async node function that:
    1. Loads node configuration via NodeLoader
    2. Creates a DualAgentNode instance
    3. Executes the node with pipeline state
    4. Updates state with deliverable, questions, evaluations
    5. Tracks iteration count
    6. Adds node to completed_nodes on APPROVED verdict

    Args:
        node_id: The node identifier (e.g., 'analyst', 'pm', 'ux', 'architect', 'po')
        session_manager: KimiSessionManager for SDK interactions.

    Returns:
        An async function that accepts PipelineState and returns updated PipelineState
    """
    # Create logger with node_id bound
    logger = structlog.get_logger().bind(node_id=node_id)

    async def node_executor(state: PipelineState) -> PipelineState:
        """Async node executor function for LangGraph.

        Args:
            state: The current pipeline state

        Returns:
            Updated pipeline state with node results
        """
        return await _execute_node(state, node_id, session_manager, logger)

    return node_executor


async def _execute_node(
    state: PipelineState,
    node_id: str,
    session_manager: KimiSessionManager,
    logger: StructlogBoundLogger,
) -> PipelineState:
    """Execute a node and update pipeline state.

    Args:
        state: The current pipeline state
        node_id: The node identifier to execute
        session_manager: KimiSessionManager for SDK interactions.
        logger: Bound structlog logger

    Returns:
        Updated pipeline state
    """
    import copy

    from autoBMAD.docuswarm.nodes.loader import NodeLoader

    logger.info("node_execution_started", node_id=node_id)

    # Create a deep copy of state to avoid mutation of nested dicts/lists
    new_state = copy.deepcopy(state)

    # Update current_node
    new_state["current_node"] = node_id

    # Load node configuration (currently not used but kept for future validation)
    loader = NodeLoader()
    _ = loader.load(node_id)

    # Create DualAgentNode instance
    # Get config from global or create default (for now, use placeholder)
    # In production, this would come from dependency injection
    config = _get_config()

    node = create_dual_agent_node(
        config=config,
        session_manager=session_manager,
        node_id=node_id,
    )

    # Execute the node
    subject_context = state.get("subject_context", {})
    task = subject_context.get("task", "")
    # Get pipeline_id from state for IndependentAgent (Story 11.1)
    pipeline_id = state.get("pipeline_id", "")

    try:
        result = await node.execute(
            subject_context=str(subject_context),
            task=task,
            pipeline_id=pipeline_id,
        )

        # Update deliverables
        new_state["deliverables"][node_id] = result.deliverable

        # Update questions
        new_state["questions"][node_id] = result.questions

        # Update evaluations
        new_state["evaluations"][node_id] = result.evaluation

        # Update iteration count
        current_iterations = new_state["node_iterations"].get(node_id, 0)
        new_state["node_iterations"][node_id] = current_iterations + result.iteration

        # Check verdict and update completed_nodes
        verdict = result.evaluation.get("verdict") if result.evaluation else None
        if verdict == "APPROVED" or verdict == "FORCE_APPROVED":
            if node_id not in new_state["completed_nodes"]:
                new_state["completed_nodes"].append(node_id)
            logger.info(
                "node_approved", node_id=node_id, iteration=result.iteration, verdict=verdict
            )
        else:
            logger.info(
                "node_not_approved",
                node_id=node_id,
                verdict=verdict,
                iteration=result.iteration,
            )

        logger.info(
            "node_execution_completed",
            node_id=node_id,
            iteration=result.iteration,
            verdict=verdict,
        )

    except Exception as e:
        logger.error("node_execution_failed", node_id=node_id, error=str(e))
        raise

    return new_state


def _get_config():
    """Get the application config.

    In production, this would be injected via dependency injection.
    For now, reads from environment or uses defaults.
    """
    import os
    from pathlib import Path

    from autoBMAD.docuswarm.config import Config

    api_key = os.environ.get("ANTHROPIC_API_KEY", "test-api-key")
    db_path = Path(os.environ.get("DB_PATH", "docuswarm.db"))
    output_dir = Path(os.environ.get("OUTPUT_DIR", "output"))

    return Config(
        api_key=api_key,
        db_path=db_path,
        output_dir=output_dir,
        log_level=os.environ.get("LOG_LEVEL", "INFO"),
    )
