"""Dual-Agent Node Implementation - Story 2.9.

This module provides the DualAgentNode class which:
- Coordinates Independent and Evaluator agents
- Filters private_reasoning from Independent Agent output before passing to Evaluator
- Supports iteration loop when Evaluator returns NEEDS_REVISION verdict
- Passes previous feedback to Independent Agent on retry iterations
- Tracks and reports iteration count in final result
- Handles edge cases where Independent Agent returns malformed output
- Ensures Evaluator never receives private_reasoning field
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import structlog

# Beijing timezone (UTC+8)
_BEIJING_TZ = timezone(timedelta(hours=8))

if TYPE_CHECKING:
    from structlog import BoundLogger as StructlogBoundLogger

    from autoBMAD.docuswarm.node_execution.contracts import NodeExecutionContext

from autoBMAD.docuswarm.agents.evaluator import EvaluatorAgent
from autoBMAD.docuswarm.agents.independent import IndependentAgent
from autoBMAD.docuswarm.context.audit import IsolationAuditLogger
from autoBMAD.docuswarm.context.filter import ContextFilter
from autoBMAD.docuswarm.context.isolation import ContextIsolationError, ContextManager
from autoBMAD.docuswarm.llm.session_manager import SessionManager
from autoBMAD.docuswarm.nodes.iteration import IterationController
from autoBMAD.docuswarm.pipeline.escalation import EscalationHandler, EscalationReason
from autoBMAD.docuswarm.pipeline.force_completion import (
    ForceCompletion,
    create_force_completion,
)
from autoBMAD.docuswarm.pipeline.metrics import MetricsCollector
from autoBMAD.docuswarm.pipeline.quality import QualityConfig, VerdictDeterminer
from autoBMAD.docuswarm.pipeline.questions import QuestionHandler

# Type alias for force completion (optional, for type hints)
ForceCompletionRecord = ForceCompletion | None

# Type aliases for better type inference
IndependentOutput = dict[str, Any]
EvaluatorOutput = dict[str, Any]


@dataclass
class NodeResult:
    """Result from DualAgentNode execution.

    Attributes:
        deliverable: The deliverable created by Independent Agent.
        documents: List of all documents (for multi-document workflows).
        questions: Questions generated by Independent Agent.
        evaluation: Evaluation result from Evaluator Agent.
        iteration: Number of iterations executed (1-indexed).
        timestamp: Execution timestamp.
        force_completion: Force completion record if triggered (optional).
    """

    deliverable: dict[str, Any]
    questions: list[dict[str, Any]]
    evaluation: dict[str, Any]
    iteration: int
    timestamp: datetime
    force_completion: ForceCompletion | None = None
    documents: list[dict[str, Any]] = field(default_factory=list)  # F3: 多文档支持

    @property
    def is_multi_document(self) -> bool:
        """Check if result contains multiple documents."""
        return len(self.documents) > 1 or (
            self.deliverable.get("type") == "multi-document"
        )

    @property
    def all_documents(self) -> list[dict[str, Any]]:
        """Get all documents (single or multi)."""
        if self.documents:
            return self.documents
        if self.deliverable.get("type") == "multi-document":
            return self.deliverable.get("documents", [])
        return [self.deliverable] if self.deliverable else []


class DualAgentNodeError(Exception):
    """Base exception for DualAgentNode errors."""

    pass


class IndependentExecutionError(DualAgentNodeError):
    """Raised when Independent Agent execution fails."""

    pass


class EvaluatorExecutionError(DualAgentNodeError):
    """Raised when Evaluator Agent execution fails."""

    pass


class EscalationError(DualAgentNodeError):
    """Raised when node execution is blocked and requires escalation."""

    pass


class DualAgentNode:
    """Dual-Agent Node for coordinating Independent and Evaluator agents.

    This node executes a dual-agent pattern:
    1. Execute Independent Agent to generate deliverable and questions
    2. Filter private_reasoning from Independent output
    3. Execute Evaluator Agent to score the deliverable
    4. If NEEDS_REVISION, iterate with feedback (up to max_iterations)
    5. Return combined result

    Attributes:
        node_id: The node identifier.
        independent_agent: The Independent Agent instance.
        evaluator_agent: The Evaluator Agent instance.
        max_iterations: Maximum number of iteration cycles.
    """

    DEFAULT_MAX_ITERATIONS = 3

    def __init__(
        self,
        config: Any,  # Actually Config, but config package uses dynamic import
        independent_agent: IndependentAgent,
        evaluator_agent: EvaluatorAgent,
        node_id: str,
        max_iterations: int = DEFAULT_MAX_ITERATIONS,
        context_manager: ContextManager | None = None,
        context_filter: ContextFilter | None = None,
        audit_logger: IsolationAuditLogger | None = None,
        # Quality control components (Story 5.8)
        iteration_controller: IterationController | None = None,
        question_handler: QuestionHandler | None = None,
        escalation_handler: EscalationHandler | None = None,
        metrics_collector: MetricsCollector | None = None,
        quality_config: QualityConfig | None = None,
    ) -> None:
        """Initialize the DualAgentNode.

        Args:
            config: Agent configuration object.
            independent_agent: The Independent Agent instance.
            evaluator_agent: The Evaluator Agent instance.
            node_id: The node identifier.
            max_iterations: Maximum number of iteration cycles (default: 3).
            context_manager: ContextManager for building agent contexts (optional).
            context_filter: ContextFilter for removing private fields (optional).
            audit_logger: IsolationAuditLogger for auditing operations (optional).
            iteration_controller: IterationController for tracking iterations (optional).
            question_handler: QuestionHandler for collecting questions (optional).
            escalation_handler: EscalationHandler for handling escalations (optional).
            metrics_collector: MetricsCollector for recording metrics (optional).
            quality_config: QualityConfig for verdict determination (optional).
        """
        self.config = config
        self.independent_agent = independent_agent
        self.evaluator_agent = evaluator_agent
        self.node_id = node_id
        self.max_iterations = max_iterations

        # Isolation components - use defaults if not provided
        self.context_manager = context_manager or ContextManager()
        self.context_filter = context_filter or ContextFilter()
        self.audit_logger = audit_logger or IsolationAuditLogger()

        # Quality control components (Story 5.8)
        self.iteration_controller = iteration_controller
        self.question_handler = question_handler
        self.escalation_handler = escalation_handler
        self.metrics_collector = metrics_collector
        self.quality_config = quality_config or QualityConfig()

        self.logger: StructlogBoundLogger = structlog.get_logger().bind(
            node=self.__class__.__name__,
            node_id=node_id,
        )

    def _filter_for_evaluator(self, independent_output: IndependentOutput) -> IndependentOutput:
        """Filter Independent Agent output to remove private_reasoning.

        This is CRITICAL for security - private_reasoning must NEVER reach Evaluator.

        Args:
            independent_output: Raw output from Independent Agent.

        Returns:
            Filtered dict without private_reasoning field.
        """
        filtered: IndependentOutput = {}

        # Copy deliverable
        if "deliverable" in independent_output:
            deliverable = independent_output["deliverable"]
            assert isinstance(deliverable, dict)
            filtered["deliverable"] = deliverable.copy()

        # Copy questions
        if "questions" in independent_output:
            questions = independent_output["questions"]
            assert isinstance(questions, list)
            filtered["questions"] = questions.copy()

        # Explicitly exclude private_reasoning
        # (already excluded by not copying it)

        return filtered

    def _build_independent_context(
        self,
        subject_context: str,
        task: str,
        previous_feedback: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Build context for Independent Agent execution.

        Args:
            subject_context: The subject/context of the task.
            task: The task description.
            previous_feedback: Optional feedback from previous iteration.

        Returns:
            Context dict for Independent Agent.
        """
        context: dict[str, Any] = {
            "subject_context": subject_context,
            "task": task,
        }

        # Add previous feedback if available
        if previous_feedback:
            issues_found: list[str] = previous_feedback.get("issues_found", [])
            suggestions: list[str] = previous_feedback.get("suggestions", [])
            verdict: str = previous_feedback.get("verdict", "UNKNOWN")
            alignment_score: float = previous_feedback.get("alignment_score", 0.0)

            feedback_text = f"""
## Previous Feedback

The previous attempt received the following feedback:

**Verdict**: {verdict}
**Alignment Score**: {alignment_score}

**Issues Found**:
{chr(10).join(f"- {issue}" for issue in issues_found)}

**Suggestions**:
{chr(10).join(f"- {suggestion}" for suggestion in suggestions)}

Please address these issues in your revised deliverable.
"""
            context["task"] = task + feedback_text

        return context

    async def execute_with_context(
        self,
        execution_context: NodeExecutionContext,
    ) -> NodeResult:
        """Execute the dual-agent pattern using NodeExecutionContext (Single Context Protocol).

        This method implements the dual-agent pattern with the unified context protocol:
        1. Build Independent Agent input from NodeExecutionContext using ContextManager
        2. Execute Independent Agent to generate deliverable and questions
        3. Filter private fields using ContextFilter
        4. Build Evaluator Agent input from NodeExecutionContext
        5. Execute Evaluator Agent to score the deliverable
        6. If NEEDS_REVISION, iterate with feedback (up to max_iterations)
        7. Return combined result with audit logging

        Args:
            execution_context: The unified NodeExecutionContext containing all
                node configuration and runtime state.

        Returns:
            NodeResult containing deliverable, questions, evaluation, iteration, and timestamp.

        Raises:
            DualAgentNodeError: If execution fails.
            ContextIsolationError: If private fields leak to Evaluator.
        """
        pipeline_id = execution_context.get("pipeline_id", "")

        self.logger.info(
            "starting_dual_agent_execution_with_context",
            node_id=self.node_id,
            node_name=execution_context.get("node_name", ""),
        )

        iteration = 0
        previous_feedback: dict[str, Any] | None = None
        final_deliverable: dict[str, Any] = {}
        all_deliverables: list[dict[str, Any]] = []  # F3: 收集所有文档
        final_questions: list[dict[str, Any]] = []
        final_evaluation: dict[str, Any] = {}
        final_force_completion: ForceCompletion | None = None

        while iteration < self.max_iterations:
            iteration += 1

            self.logger.info(
                "iteration_start",
                iteration=iteration,
                max_iterations=self.max_iterations,
            )

            # Step 1: Build Independent Agent input and execute
            try:
                # Log context build for Independent Agent
                self.audit_logger.log_context_build(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={
                        "node_name": execution_context.get("node_name", ""),
                        "has_feedback": previous_feedback is not None,
                    },
                )

                # Build IndependentAgentInput using ContextManager (Single Context Protocol)
                independent_input = self.context_manager.build_independent_input(
                    execution_context=execution_context,
                    iteration_feedback=previous_feedback,
                )

                # Execute Independent Agent with structured input
                # RC-3 Fix: 传递可配置的 timeout 参数
                independent_output = await self.independent_agent.execute_with_input(
                    agent_input=independent_input,
                    pipeline_id=pipeline_id,
                    timeout=getattr(self.config, "agent_timeout", 300),
                )

                # Handle potentially malformed output with defaults
                # F3: 处理多文档结果
                independent_deliverable = independent_output.get("deliverable")
                if isinstance(independent_deliverable, dict):
                    final_deliverable.clear()
                    final_deliverable.update(cast(dict[str, Any], independent_deliverable))

                    # F3: 检查是否为多文档格式
                    if independent_deliverable.get("type") == "multi-document":
                        # 多文档：提取 documents 列表
                        all_deliverables = independent_deliverable.get("documents", [])
                    else:
                        # 单文档：包装为列表
                        all_deliverables = [independent_deliverable]

                independent_questions = independent_output.get("questions")
                if isinstance(independent_questions, list):
                    final_questions.clear()
                    final_questions.extend(cast(list[dict[str, Any]], independent_questions))

            except Exception as e:
                self.logger.error("independent_agent_failed", iteration=iteration, error=str(e))
                raise IndependentExecutionError(
                    f"Independent Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 2: Filter private fields before passing to Evaluator
            try:
                filtered_output = self.context_filter.filter_for_evaluator(independent_output)

                # Log filter operation
                fields_removed = [
                    field
                    for field in [
                        "private_reasoning",
                        "tool_call_history",
                        "internal_notes",
                        "iteration_feedback",
                    ]
                    if field in independent_output
                ]
                self.audit_logger.log_filter_operation(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    fields_removed=fields_removed,
                )

            except Exception as e:
                self.logger.error("filter_operation_failed", iteration=iteration, error=str(e))
                self.audit_logger.log_potential_violation(
                    agent_type="independent",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={"error": str(e), "stage": "filter"},
                )
                raise

            # Step 3: Build Evaluator input and execute
            try:
                # Log context build for Evaluator Agent
                self.audit_logger.log_context_build(
                    agent_type="evaluator",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={
                        "deliverable_keys": list(filtered_output.get("deliverable", {}).keys())
                    },
                )

                # Build EvaluatorAgentInput using ContextManager (Single Context Protocol)
                evaluator_input = self.context_manager.build_evaluator_input(
                    execution_context=execution_context,
                    deliverable=filtered_output.get("deliverable"),
                )

                # Execute Evaluator Agent with structured input
                evaluation = await self.evaluator_agent.execute_with_input(evaluator_input)
                final_evaluation = evaluation

            except ContextIsolationError as e:
                # Log potential violation
                self.logger.error(
                    "context_isolation_violation",
                    iteration=iteration,
                    error=str(e),
                )
                self.audit_logger.log_potential_violation(
                    agent_type="evaluator",
                    pipeline_id=pipeline_id,
                    node_id=self.node_id,
                    details={"error": str(e), "stage": "context_build"},
                )
                raise

            except Exception as e:
                self.logger.error("evaluator_agent_failed", iteration=iteration, error=str(e))
                raise EvaluatorExecutionError(
                    f"Evaluator Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 4: Check verdict and decide if we need to iterate
            verdict: str = evaluation.get("verdict", "NEEDS_REVISION")

            self.logger.info(
                "evaluation_complete",
                iteration=iteration,
                verdict=verdict,
                alignment_score=evaluation.get("alignment_score", 0.0),
            )

            if verdict == "APPROVED":
                # Success - exit the loop
                self.logger.info(
                    "dual_agent_approved",
                    iteration=iteration,
                )
                break
            elif verdict == "FORCE_APPROVED":
                # Force complete - exit the loop with warning
                alignment_score: float = evaluation.get("alignment_score", 0.0)
                issues_list: list[Any] = evaluation.get("issues_found", [])

                # Create force completion record
                final_force_completion = create_force_completion(
                    node_id=self.node_id,
                    final_score=alignment_score,
                    threshold=0.50,  # Default escalation threshold
                    iterations=iteration,
                    issues_remaining=[str(i) for i in issues_list],
                )

                # Log the force completion warning
                self.logger.warning(
                    "force_completion_triggered",
                    node_id=self.node_id,
                    iteration=iteration,
                    alignment_score=alignment_score,
                    force_complete_warning=final_force_completion.warning,
                )
                break
            elif verdict == "BLOCKED":
                # Can't proceed - exit the loop
                self.logger.warning(
                    "dual_agent_blocked",
                    iteration=iteration,
                )
                break
            else:
                # NEEDS_REVISION - prepare for next iteration
                eval_alignment_score: float = evaluation.get("alignment_score", 0.0)
                eval_issues_found: list[Any] = evaluation.get("issues_found", [])
                eval_suggestions: list[Any] = evaluation.get("suggestions", [])

                previous_feedback = {
                    "alignment_score": eval_alignment_score,
                    "verdict": verdict,
                    "issues_found": eval_issues_found,
                    "suggestions": eval_suggestions,
                }

                self.logger.info(
                    "iteration_needs_revision",
                    iteration=iteration,
                    preparing_for_next=True,
                )

        # Return the combined result
        # F3: 包含多文档支持
        result = NodeResult(
            deliverable=final_deliverable,
            documents=all_deliverables,  # F3: 包含所有文档
            questions=final_questions,
            evaluation=final_evaluation,
            iteration=iteration,
            timestamp=datetime.now(_BEIJING_TZ),
            force_completion=final_force_completion,
        )

        self.logger.info(
            "dual_agent_execution_complete",
            iteration=iteration,
            verdict=final_evaluation.get("verdict", "UNKNOWN"),
        )

        return result

    async def execute_with_iteration(
        self,
        state: dict[str, Any],
    ) -> NodeResult:
        """Execute node with full iteration and quality control (Story 5.8).

        This method implements the iteration loop with quality control:
        1. Start iteration using IterationController
        2. Get accumulated feedback from previous iterations
        3. Execute single iteration (Independent + Evaluator)
        4. Collect questions using QuestionHandler
        5. Record iteration using IterationController
        6. Determine verdict using VerdictDeterminer
        7. Handle verdict (APPROVED/FORCE_APPROVED/BLOCKED/NEEDS_REVISION)
        8. Record metrics using MetricsCollector
        9. Escalate on BLOCKED verdict

        Args:
            state: Pipeline state dict containing pipeline_id, subject_context, task.

        Returns:
            NodeResult containing deliverable, questions, evaluation, iteration, and timestamp.

        Raises:
            EscalationError: When BLOCKED verdict occurs after max iterations.
        """
        if not self.iteration_controller:
            raise DualAgentNodeError("IterationController is required for execute_with_iteration")

        pipeline_id = state.get(
            "pipeline_id", f"{self.node_id}_{datetime.now(_BEIJING_TZ).strftime('%Y%m%d%H%M%S')}"
        )
        subject_context = state.get("subject_context", "")
        task = state.get("task", "")

        final_deliverable: dict[str, Any] = {}
        final_questions: list[dict[str, Any]] = []
        final_evaluation: dict[str, Any] = {}
        final_force_completion: ForceCompletion | None = None
        result: NodeResult | None = None

        # Create verdict determiner
        verdict_determiner = VerdictDeterminer(self.quality_config)

        while True:
            # Start iteration
            iteration = self.iteration_controller.start_iteration(self.node_id)

            self.logger.info(
                "iteration_start",
                iteration=iteration,
                max_iterations=self.max_iterations,
            )

            # Get accumulated feedback and build execution context
            accumulated_feedback = self.iteration_controller.get_accumulated_feedback(self.node_id)

            from autoBMAD.docuswarm.node_execution.context_builder import create_context_builder

            # Build original_context from subject_context and task
            original_context: dict[str, Any] = {}
            if isinstance(subject_context, dict):
                original_context = dict(subject_context)
            elif subject_context:
                original_context = {"content": str(subject_context)}

            if task:
                original_context.setdefault("task", task)
                original_context.setdefault("content", task)

            execution_context = create_context_builder().build(
                pipeline_id=pipeline_id,
                node_id=self.node_id,
                original_context=original_context,
                iteration_feedback=accumulated_feedback,
            )

            # Step 1: Execute Independent Agent
            try:
                independent_input = self.context_manager.build_independent_input(
                    execution_context=execution_context,
                    iteration_feedback=accumulated_feedback,
                )
                independent_output = await self.independent_agent.execute_with_input(
                    agent_input=independent_input,
                    pipeline_id=pipeline_id,
                )

                # Handle potentially malformed output with defaults
                independent_deliverable = independent_output.get("deliverable")
                if isinstance(independent_deliverable, dict):
                    final_deliverable.clear()
                    final_deliverable.update(cast(dict[str, Any], independent_deliverable))

                independent_questions = independent_output.get("questions")
                if isinstance(independent_questions, list):
                    final_questions.clear()
                    final_questions.extend(cast(list[dict[str, Any]], independent_questions))

            except Exception as e:
                self.logger.error("independent_agent_failed", iteration=iteration, error=str(e))
                raise IndependentExecutionError(
                    f"Independent Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 2: Filter and execute Evaluator Agent
            try:
                filtered_output = self.context_filter.filter_for_evaluator(independent_output)

                evaluator_input = self.context_manager.build_evaluator_input(
                    execution_context=execution_context,
                    deliverable=filtered_output.get("deliverable"),
                )

                evaluation = await self.evaluator_agent.execute_with_input(evaluator_input)
                final_evaluation = evaluation

            except ContextIsolationError as e:
                self.logger.error("context_isolation_violation", iteration=iteration, error=str(e))
                raise
            except Exception as e:
                self.logger.error("evaluator_agent_failed", iteration=iteration, error=str(e))
                raise EvaluatorExecutionError(
                    f"Evaluator Agent failed on iteration {iteration}: {e}"
                ) from e

            # Step 3: Collect questions
            if self.question_handler and final_questions:
                # Transform question format from {question, priority, context} to {question_text, priority, context}
                transformed_questions: list[dict[str, Any]] = []
                for q in final_questions:
                    transformed_q = {**q, "node_id": self.node_id}
                    if "question" in transformed_q and "question_text" not in transformed_q:
                        transformed_q["question_text"] = transformed_q.pop("question")
                    transformed_questions.append(transformed_q)
                self.question_handler.collect_questions(
                    pipeline_id,
                    transformed_questions,
                )

            # Step 4: Record iteration
            self.iteration_controller.record_iteration(
                node_id=self.node_id,
                verdict=evaluation.get("verdict", "NEEDS_REVISION"),
                alignment_score=evaluation.get("alignment_score", 0.0),
                issues=evaluation.get("issues_found", []),
                suggestions=evaluation.get("suggestions", []),
            )

            # Step 5: Determine verdict using VerdictDeterminer
            alignment_score = evaluation.get("alignment_score", 0.0)
            raw_verdict = evaluation.get("verdict", "NEEDS_REVISION")

            # If raw verdict is already terminal, use it directly
            if raw_verdict in ("APPROVED", "FORCE_APPROVED", "BLOCKED"):
                verdict = raw_verdict
            else:
                # Use VerdictDeterminer to determine verdict
                determined = verdict_determiner.determine_verdict(
                    alignment_score=alignment_score,
                    node_id=self.node_id,
                    iteration=iteration,
                    max_iterations=self.max_iterations,
                )
                verdict = determined.value

            # Update evaluation with determined verdict
            final_evaluation["verdict"] = verdict

            # Step 6: Handle verdict
            if verdict == "APPROVED":
                self.logger.info("iteration_approved", iteration=iteration)
                # Record metrics
                if self.metrics_collector:
                    self.metrics_collector.record_node_completion(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        final_score=alignment_score,
                        iterations=iteration,
                        verdict=verdict,
                        force_completed=False,
                    )
                result = NodeResult(
                    deliverable=final_deliverable,
                    questions=final_questions,
                    evaluation=final_evaluation,
                    iteration=iteration,
                    timestamp=datetime.now(_BEIJING_TZ),
                    force_completion=None,
                )
                break

            elif verdict == "FORCE_APPROVED":
                self.logger.warning("iteration_force_approved", iteration=iteration)
                alignment_score_val = evaluation.get("alignment_score", 0.0)
                issues_list = evaluation.get("issues_found", [])

                # Get node-specific thresholds for force completion record
                node_thresholds = self.quality_config.get_thresholds(self.node_id)

                # Create force completion record
                final_force_completion = create_force_completion(
                    node_id=self.node_id,
                    final_score=alignment_score_val,
                    threshold=node_thresholds.escalation,
                    iterations=iteration,
                    issues_remaining=[str(i) for i in issues_list],
                )

                # Record metrics with force_completed=True
                if self.metrics_collector:
                    self.metrics_collector.record_node_completion(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        final_score=alignment_score_val,
                        iterations=iteration,
                        verdict=verdict,
                        force_completed=True,
                    )

                result = NodeResult(
                    deliverable=final_deliverable,
                    questions=final_questions,
                    evaluation=final_evaluation,
                    iteration=iteration,
                    timestamp=datetime.now(_BEIJING_TZ),
                    force_completion=final_force_completion,
                )
                break

            elif verdict == "BLOCKED":
                self.logger.error("iteration_blocked", iteration=iteration)
                # Trigger escalation
                if self.escalation_handler:
                    await self.escalation_handler.escalate(
                        pipeline_id=pipeline_id,
                        node_id=self.node_id,
                        reason=EscalationReason.MAX_ITERATIONS,
                        alignment_score=alignment_score,
                        issues=evaluation.get("issues_found", []),
                    )
                raise EscalationError(f"Node {self.node_id} blocked - escalation required")

            # NEEDS_REVISION - continue loop if should iterate
            if not self.iteration_controller.should_iterate(self.node_id):
                self.logger.warning("max_iterations_reached_no_approval")
                # At max iterations without approval - determine final state using node-specific thresholds
                node_thresholds = self.quality_config.get_thresholds(self.node_id)
                if alignment_score >= node_thresholds.escalation:
                    verdict = "FORCE_APPROVED"
                    self.logger.warning("force_approved_at_max_iterations", score=alignment_score)
                    if self.metrics_collector:
                        self.metrics_collector.record_node_completion(
                            pipeline_id=pipeline_id,
                            node_id=self.node_id,
                            final_score=alignment_score,
                            iterations=iteration,
                            verdict=verdict,
                            force_completed=True,
                        )
                    result = NodeResult(
                        deliverable=final_deliverable,
                        questions=final_questions,
                        evaluation=final_evaluation,
                        iteration=iteration,
                        timestamp=datetime.now(_BEIJING_TZ),
                        force_completion=final_force_completion,
                    )
                else:
                    verdict = "BLOCKED"
                    self.logger.error("blocked_at_max_iterations", score=alignment_score)
                    if self.escalation_handler:
                        await self.escalation_handler.escalate(
                            pipeline_id=pipeline_id,
                            node_id=self.node_id,
                            reason=EscalationReason.MAX_ITERATIONS,
                            alignment_score=alignment_score,
                            issues=evaluation.get("issues_found", []),
                        )
                    raise EscalationError(
                        f"Node {self.node_id} blocked at max iterations - escalation required"
                    )
                break

            # Prepare feedback for next iteration
            self.logger.info(
                "iteration_needs_revision",
                iteration=iteration,
                preparing_for_next=True,
            )

        return result


def create_dual_agent_node(
    config: Any,  # Actually Config, but config package uses dynamic import
    session_manager: SessionManager,
    node_id: str,
    project_root: Path | None = None,
    max_iterations: int | None = None,
) -> DualAgentNode:
    """Create a DualAgentNode with configured agents.

    P0 Fix: max_iterations now defaults to None, which triggers loading from node config.

    Args:
        config: Agent configuration.
        session_manager: SessionManager for SDK interactions.
        node_id: The node identifier for persona/criteria loading.
        project_root: Root directory of the project.
        max_iterations: Maximum number of iteration cycles. If None, loaded from node config.

    Returns:
        Configured DualAgentNode instance.
    """
    from autoBMAD.docuswarm.agents.evaluator import create_evaluator_agent
    from autoBMAD.docuswarm.agents.independent import create_independent_agent
    from autoBMAD.nodes.loader import NodeLoader

    # P0 Fix: Load max_iterations from node config if not explicitly provided
    if max_iterations is None:
        try:
            node_config = NodeLoader.load(node_id)
            if node_config.evaluator:
                max_iterations = node_config.evaluator.max_iterations
            else:
                max_iterations = DualAgentNode.DEFAULT_MAX_ITERATIONS
        except Exception:
            # Fall back to default if loading fails
            max_iterations = DualAgentNode.DEFAULT_MAX_ITERATIONS

    # Create agents using convenience functions
    independent_agent = create_independent_agent(
        config=config,
        session_manager=session_manager,
        node_id=node_id,
        project_root=project_root,
    )

    evaluator_agent = create_evaluator_agent(
        config=config,
        session_manager=session_manager,
        node_id=node_id,
        project_root=project_root,
    )

    return DualAgentNode(
        config=config,
        independent_agent=independent_agent,
        evaluator_agent=evaluator_agent,
        node_id=node_id,
        max_iterations=max_iterations,
    )


__all__ = [
    "DualAgentNode",
    "DualAgentNodeError",
    "IndependentExecutionError",
    "EvaluatorExecutionError",
    "EscalationError",
    "NodeResult",
    "create_dual_agent_node",
]
