"""Question Handling - Story 5.4.

This module provides the QuestionPriority enum, Question dataclass, and QuestionHandler
class for managing questions from agents in the pipeline.

Features:
- Question prioritization (BLOCKING, CLARIFYING, OPTIONAL)
- Question collection and storage with unique IDs
- Answer management with timestamp tracking
- Integration with StateManager for context updates
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import TYPE_CHECKING, Any

# Beijing timezone (UTC+8)
_BEIJING_TZ = timezone(timedelta(hours=8))

if TYPE_CHECKING:
    from autoBMAD.docuswarm.storage.state_manager import StateManager

logger = logging.getLogger(__name__)


class QuestionPriority(Enum):
    """Question priority levels.

    Attributes:
        BLOCKING: Questions that prevent pipeline progression until answered.
        CLARIFYING: Questions that clarify requirements but don't block progress.
        OPTIONAL: Questions that are nice to have but don't affect execution.
    """

    BLOCKING = "BLOCKING"
    CLARIFYING = "CLARIFYING"
    OPTIONAL = "OPTIONAL"


@dataclass
class Question:
    """Represents a question from an agent.

    Attributes:
        question_id: Unique identifier in format {pipeline_id}_{node_id}_{index}.
        pipeline_id: The pipeline this question belongs to.
        node_id: The node that generated the question.
        question_text: The actual question text.
        priority: The priority level of the question.
        context: Additional context information.
        created_at: Timestamp when the question was created.
        answer: The answer to the question (None if unanswered).
        answered_at: Timestamp when the question was answered (None if unanswered).
    """

    question_id: str
    pipeline_id: str
    node_id: str
    question_text: str
    priority: QuestionPriority
    context: dict[str, Any]
    created_at: datetime
    answer: str | None = None
    answered_at: datetime | None = None


class QuestionHandler:
    """Handles question collection, storage, and answering.

    This class manages questions generated by agents during pipeline execution,
    supports prioritization, and integrates with StateManager to update subject
    context when questions are answered.

    Args:
        state_manager: StateManager instance for context updates.

    Example:
        >>> handler = QuestionHandler(state_manager=state_manager)
        >>> handler.collect_questions("pipeline-123", questions_data)
        >>> handler.has_blocking_questions("pipeline-123")
        True
        >>> handler.answer_question("pipeline-123", "pipeline-123_node_0", "Answer")
    """

    def __init__(self, state_manager: StateManager | None = None) -> None:
        """Initialize QuestionHandler.

        Args:
            state_manager: StateManager instance for context updates. Can be None
                         for testing purposes.
        """
        self._state_manager = state_manager
        self._questions: dict[str, list[Question]] = {}

    def collect_questions(
        self, pipeline_id: str, questions_data: list[dict[str, Any]]
    ) -> list[Question]:
        """Collect and store questions for a pipeline.

        Creates Question objects from the provided data and stores them keyed
        by pipeline_id. Question IDs are generated in format:
        {pipeline_id}_{node_id}_{index}

        Args:
            pipeline_id: The pipeline ID to associate questions with.
            questions_data: List of question dictionaries with keys:
                - node_id: ID of the node generating the question
                - question_text: The question text
                - priority: Priority level ("BLOCKING", "CLARIFYING", "OPTIONAL")
                - context: Additional context dictionary

        Returns:
            List of created Question objects.

        Example:
            >>> questions_data = [
            ...     {
            ...         "node_id": "analyst",
            ...         "question_text": "What is the target audience?",
            ...         "priority": "BLOCKING",
            ...         "context": {"subject": "Test"}
            ...     }
            ... ]
            >>> handler.collect_questions("pipeline-123", questions_data)
        """
        if pipeline_id not in self._questions:
            self._questions[pipeline_id] = []

        questions: list[Question] = []
        current_index = len(self._questions[pipeline_id])

        for q_data in questions_data:
            priority_str = q_data.get("priority", "OPTIONAL").upper()
            try:
                priority = QuestionPriority[priority_str]
            except KeyError:
                logger.warning(
                    f"Invalid priority '{priority_str}' for question, defaulting to OPTIONAL"
                )
                priority = QuestionPriority.OPTIONAL

            question = Question(
                question_id=f"{pipeline_id}_{q_data['node_id']}_{current_index}",
                pipeline_id=pipeline_id,
                node_id=q_data["node_id"],
                question_text=q_data["question_text"],
                priority=priority,
                context=q_data.get("context", {}),
                created_at=datetime.now(_BEIJING_TZ),
            )

            self._questions[pipeline_id].append(question)
            questions.append(question)
            current_index += 1

            logger.info(f"Collected question {question.question_id} with priority {priority.value}")

        return questions

    def get_unanswered_questions(
        self,
        pipeline_id: str,
        priority: QuestionPriority | None = None,
        run_id: str | None = None,
    ) -> list[Question]:
        """Get unanswered questions for a pipeline, optionally filtered by priority or run.

        Args:
            pipeline_id: The pipeline ID to get questions for.
            priority: Optional priority level to filter by.
            run_id: Optional run ID to filter by. If not provided, returns questions
                    from the latest run.

        Returns:
            List of unanswered Question objects matching the criteria.
        """
        pipeline_questions = self._questions.get(pipeline_id, [])

        unanswered = [q for q in pipeline_questions if q.answer is None]

        # Filter by run_id if provided
        if run_id is not None:
            # Question IDs are in format: {pipeline_id}_{node_id}_{index}
            # Run ID is part of the question_id, typically at the end
            unanswered = [q for q in unanswered if run_id in q.question_id]

        if priority is not None:
            unanswered = [q for q in unanswered if q.priority == priority]

        return unanswered

    def has_blocking_questions(self, pipeline_id: str) -> bool:
        """Check if pipeline has any unanswered blocking questions.

        Args:
            pipeline_id: The pipeline ID to check.

        Returns:
            True if there are unanswered blocking questions, False otherwise.
        """
        unanswered = self.get_unanswered_questions(pipeline_id)
        return any(q.priority == QuestionPriority.BLOCKING for q in unanswered)

    async def answer_question(self, pipeline_id: str, question_id: str, answer: str) -> Question:
        """Record an answer to a question.

        Args:
            pipeline_id: The pipeline ID the question belongs to.
            question_id: The unique question ID.
            answer: The answer text.

        Returns:
            The updated Question object.

        Raises:
            ValueError: If the question is not found.
        """
        pipeline_questions = self._questions.get(pipeline_id, [])

        question: Question | None = None
        for q in pipeline_questions:
            if q.question_id == question_id:
                question = q
                break

        if question is None:
            raise ValueError(f"Question not found: {question_id}")

        question.answer = answer
        question.answered_at = datetime.now(_BEIJING_TZ)

        logger.info(f"Answered question {question_id} for pipeline {pipeline_id}")

        # Incorporate answer into subject context
        await self._incorporate_answer(pipeline_id, question, answer)

        return question

    async def _incorporate_answer(self, pipeline_id: str, question: Question, answer: str) -> None:
        """Incorporate a question answer into the pipeline subject context.

        Args:
            pipeline_id: The pipeline ID.
            question: The answered question.
            answer: The answer text.
        """
        if self._state_manager is None:
            logger.debug(
                f"No StateManager available, skipping context update for {question.question_id}"
            )
            return

        try:
            # Build context update with question and answer
            context_update = {
                f"question_{question.question_id}": {
                    "question": question.question_text,
                    "answer": answer,
                    "node_id": question.node_id,
                    "priority": question.priority.value,
                }
            }

            # Call StateManager to update subject context
            self._state_manager.update_subject_context(
                pipeline_id=pipeline_id, context_update=context_update
            )

            logger.info(f"Incorporated answer for {question.question_id} into pipeline context")
        except Exception as e:
            logger.error(
                f"Failed to incorporate answer into context: {e}",
                extra={"pipeline_id": pipeline_id, "question_id": question.question_id},
            )
            # Don't raise - answer is still recorded even if context update fails
